# Generated by Django 6.0 on 2025-12-16 14:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('matches', '0001_initial'),
        ('players', '0001_initial'),
        ('stats', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Performance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('goals', models.PositiveIntegerField(default=0)),
                ('assists', models.PositiveIntegerField(default=0)),
                ('shots', models.PositiveIntegerField(default=0)),
                ('passes', models.PositiveIntegerField(default=0)),
                ('minutes_played', models.PositiveIntegerField()),
                ('rating', models.DecimalField(decimal_places=1, max_digits=3)),
                ('match', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='performances', to='matches.match')),
                ('player', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='performances', to='players.player')),
            ],
        ),
        migrations.DeleteModel(
            name='PlayerStats',
        ),
    ]
